### ISSUE TITLE
Removed objects are not returned in query 

### ISSUE THREAD

**Issue by juliccr** [googleads/google-ads-java#134]
Hi! We are trying to migrate to the new Google Ads API. Our use case is that we keep a local sync of the objects. When we query the `change_status` resource  the REMOVED resources (for example: ad_group_criterion) are returned with the status 'REMOVED'. 
The query is: 
```
SELECT change_status.ad_group_criterion,
       change_status.resource_type, 
       change_status.last_change_date_time 
  FROM change_status
 WHERE change_status.last_change_date_time >= '2019-06-01 10:00:00' 
   AND change_status.resource_type = 'AD_GROUP_CRITERION' ;
```

But when we then query filtering by the resource_name that has been deleted (returned by the first query), that same resource is not brought by the API. 

```
"SELECT ad_group_criterion.criterion_id , 
       ad_group_criterion.status, ad_group_criterion.type, 
       ad_group_criterion.webpage.criterion_name, 
  FROM ad_group_criterion 
WHERE ad_group_criterion.resource_name = '<the resource-name obtained> '
```

How can we get those complete adgroup criterions ?

**Comment by nwbirnie** [comment]
Hey, 

I suspect this might due to either:

1) the resource_name field is not supporting filter operations (which it [should](https://developers.google.com/google-ads/api/docs/fields/ad_group_criterion#ad_group_criterionresource_name)) in which case you could try filtering by the ID rather than resource name, 

or 2) there is an implicit filter to not return removed criteria, in which case you can add a clause to the WHERE ad_group_criterion.status = 'REMOVED'.

Also in general, this tracker is for the Java client library. For product related questions, please start a thread on the [Google Ads API forum](https://groups.google.com/forum/#!forum/adwords-api).
