### ISSUE TITLE
MutateAdGroupExtensionSettings incorrectly reporting System Limit Error

### ISSUE THREAD

**Issue by mcgowanb** [googleads/google-ads-java#158]
When making a mutate call for MutateAdGroupExtensionSettings with partial Failure enabled, the error `The number of entries in the request exceeds the system limit` is being incorrectly reported via the call to `ErrorUtils.getGoogleAdsErrors`. The error returned is 118:2 rather than the correct error code
[example.txt](https://github.com/googleads/google-ads-java/files/3358998/example.txt)

**Comment by nwbirnie** [comment]
I tried deserializing the text proto provided, and calling `ErrorUtils.getGoogleAdsErrors(118, msg)`. This returns exactly one error:

```
[error_code {
  size_limit_error: REQUEST_SIZE_LIMIT_EXCEEDED
}
message: "The number of entries in the request exceeds the system limit."
trigger {
  string_value: ""
}
location {
  field_path_elements {
    field_name: "operations"
    index {
      value: 118
    }
  }
}
]
```
[Code here](https://gist.github.com/nwbirnie/3201432095ff52fe7995ffd3716d7b22)

Is this what you're seeing? If yes can you clarify the problem please? If not, can you create a short gist showing receiving the response, calling `ErrorUtils` and print the return value of `getGoogleAdsErrors()`.

**Comment by mcgowanb** [comment]
![debug](https://user-images.githubusercontent.com/7889331/60672147-8e25a880-9e6c-11e9-8d2b-56a171556387.png)
See image for this in action during debugging. `operationIndex` at this point is 0

**Comment by nwbirnie** [comment]
You're using an old version of the client library which does not contain this error code.

118:2 is the enum index into `ErrorCode.SizeLimitError.REQUEST_SIZE_LIMIT_EXCEEDED`. This was pushed with API version 1.3, so you need to use at least [3.0.0](https://github.com/googleads/google-ads-java/releases/tag/3.0.0) to decode this error. This version also refactors `ErrorUtils` to use an abstract base class, so you need to replace `ErrorUtils.getInstance()` with `ErrorUtils.getInstance().getGoogleAdsErrors()`.

There's been several bug fixes and a new major version of the API since the version you're on currently, so I would just go straight to 4.0.0.
