### ISSUE TITLE
How to give index in Final URL ? and why it need ?

### ISSUE THREAD

**Issue by thakorji007** [googleads/google-ads-java#175]
Hello sir , 

i am trying to develop create campaign API in Spring boot 
but when i trying to add Final URL in Ad class or Sitelink class then it is asking me about index, 
but it is taking two argument index and string , and when i give first argument 0 (zero) index and second argument String URL then it give me exception 
Out of bound index 

i don't know what actually value i have to give there 
can you please help me ?

================== HERE IS MY CODE WHICH I DONE IN EXAMPLE ========

Example 1 : 

Ad ad = Ad.newBuilder().setExpandedDynamicSearchAd(expandedDynamicSearchAdInfo)
				// .setFinalUrls(0,StringValue.of("htttp://www.myahmedabad.com"))
.build();

   
Example 2 : 

	public SitelinkFeedItem sendsitelinkExtension(String lineText,String line1,String line2,String finalurl) {

		return SitelinkFeedItem.newBuilder()
				.setLinkText(StringValue.of(lineText))
				.setLine1(StringValue.of(line1))
				.setLine2(StringValue.of(line2))
				 .setFinalUrls(0,StringValue.of("http://www.finalurl.com"))

				.build();

	}

==============================================================

here above both example you can see setFinalURL need to set index and string  now when i set it i will give me **out of bound index** , or no index here because second argument is String not List or any Collection.

**Comment by jradcliff** [comment]
Hi,

The `finalUrls` attribute is a collection, so you'll want to use `add` instead of `set`. Please check out [this line in the expanded text ads example](https://github.com/googleads/google-ads-java/blob/master/google-ads-examples/src/main/java/com/google/ads/googleads/examples/basicoperations/AddExpandedTextAds.java#L120) and let me know if you encounter further issues.

Thanks,
Josh, Google Ads API Team

**Comment by thakorji007** [comment]
Thank you sir ,

 it is done perfectly.
