### ISSUE TITLE
ReportDownloadE rror.ERROR_WRITING_REPORT_TO_FILE

### ISSUE THREAD

**Issue by mofa** [googleads/google-ads-java#24]
Hi ,

We suddenly are getting the below error:

HTTP Response Code: 500, Trigger: Unable to create report, Type: ReportDownloadE
rror.ERROR_WRITING_REPORT_TO_FILE

**Comment by jradcliff** [comment]
Hi,

Based on the error you mentioned, this appears to be an issue with the AdWords API. Since this issues list is for a different API (the [Google Ads API](https://developers.google.com/google-ads/api/docs/start)) and it does not appear to be a problem with the library, please post your question to the AdWords API Forum instead:

https://groups.google.com/forum/#!forum/adwords-api

Thanks,
Josh, Google Ads API Team
