### ISSUE TITLE
ReportTypes Enum + dynamic get response value by field key

### ISSUE THREAD

**Issue by ashhade** [googleads/google-ads-java#468]
Hey !!!

we use the existing ReportTypes Enum that exists in the old SDK (google adwords). We list some reports of them and when we select a report we fetch the whole fields and display it in the dropdown list.
Now my question is,

1) is there an equivalent enum (to list all reports) in the new google ads SDK ?!
2) Is the SDK support to get the  response value from GoogleAdsRow in a dynamic way, for example by segment name like googleAdsRow.get("segemnt.ad_group_ad.id") ?!

**Comment by nwbirnie** [comment]
Sadly there is not an equivalent enum in the new Google Ads API. Everything there is based on GAQL. The closest we have would be the [reference documentation](https://developers.google.com/google-ads/api/fields/v8/overview) and [interactive query builder](https://developers.google.com/google-ads/api/fields/v8/overview_query_builder). We have discussed adding something similar to the AWAPI selector builder, but so far this has come up against tough competition for resources.

There is a utility to get a field by name, it's `FieldMasks.getFieldValue()`, for example

```
import com.google.ads.googleads.lib.utils.FieldMasks;

FieldMasks.getFieldValue("ad_group_ad.id", googleAdsRow);
```

There is no need to specify `segments` before `ad_group_ad`. This is because including the field in your query implicitly segments the result by the `id`.

**Comment by ashhade** [comment]
Hey Nwbirnie
1) ok 
2) if the field name ad_group_criterion.criterion_id  or   segments.geo_target_region. or metrics.engagements. or campaign.id in the same query i can just remove the first word  to be 
criterion_id  geo_target_region engagements id ?!
because it may have many fields that aggregated between 2 or 3 tables  so it's useful to write the whole name and is the SDK know to deal with that ?!

**Comment by nwbirnie** [comment]
Sorry, that's not quite right. I was just saying that "segments.ad_group_ad.id" isn't a valid field. 

In general you can just specify the fields exactly as they appear in the `SELECT` statement. So if you have `SELECT ad_group_ad.id FROM ad_group_ad` you can specify `FieldMasks.getFieldValue("ad_group_ad.id", row)` to get the values from the row.

**Comment by ashhade** [comment]
get it thanks Nwbirnie
