### ISSUE TITLE
Connecting to Google Ads Client using Service account

### ISSUE THREAD

**Issue by deivamanikailasam** [googleads/google-ads-java#471]
Please let me know if service account can be configuration using java for accessing google ads api. If yes, Please provide examples and resources for getting started on it.

**Comment by nwbirnie** [comment]
Hey, sure we [support service accounts](https://developers.google.com/google-ads/api/docs/client-libs/java/oauth-service). However these are limited to domain-wide delegation within a GSuite domain. Generally we advise not to go down this route since it can be a [significant security risk](https://cloud.google.com/iam/docs/best-practices-for-securing-service-accounts#domain-wide-delegation).

**Comment by nwbirnie** [comment]
Closing for now, but please let me know if there's anything else we can help with.
