### ISSUE TITLE
Avoid dependency resolution issues

### ISSUE THREAD

**Issue by nwbirnie** [googleads/google-ads-java#50]
We have dependencies on some of the most commonly used libraries on the web, this will frequently lead to dependency resolution issues between us and other projects. We should investigate and provide a preemptive solution, perhaps by shading some/all dependencies into our jar.

**Comment by agustinscigliano** [comment]
Hi, I have a doubt regarding dependency resolution:
I am using the library with maven like this:
```
<dependency>
 <groupId>com.google.api-ads</groupId>
 <artifactId>google-ads</artifactId>
 <version>0.6.0</version>
</dependency>
```

The problem is that after obtaining a `GoogleAdsClient`, I want to use the method `getGoogleAdsServiceClient()`
 
And it shows the following error:
 
 `java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;CLjava/lang/Object;)V`
 
I think the error has to do with the Guava version having to be above 20.0, although including that dependency:
 
```
<dependency>
 <groupId>com.google.guava</groupId>
 <artifactId>guava</artifactId>
 <version>27.0.1-jre</version>
</dependency>
```

The problem persists, 

 
It appears the different versions are in conflict, have you seen this before?

 
Doing a: mvn dependency:tree | less | grep guava, I get the following:

[INFO] \- com.google.guava:guava:jar:27.0.1-jre:compile
[INFO]    +- com.google.guava:failureaccess:jar:1.0.1:compile
[INFO]    +- com.google.guava:listenablefuture:jar:9999.0-empty-to-avoid-conflict-with-guava:compile
[INFO] |  \- com.google.guava:guava:jar:18.0:runtime
[INFO] |  |  |  +- org.glassfish.jersey.bundles.repackaged:jersey-guava:jar:2.25.1:compile

**Comment by nwbirnie** [comment]
Hey, thanks for getting in contact. The Guava dependency for Google Ads is 26.0-android. Can you enforce this version in your project?

In general, this is something we want to address, since we have some very common dependencies, such as protobuf, Guava etc. this will frequently cause issues downstream. One option here would be to use the shade plugin to relocate these packages into an uber jar.

**Comment by nisha-goyal** [comment]
Hi @nwbirnie 
We are trying to integrate Google Ads API with a hadoop project and is causing conflict between the protobuf versions. Is there any progress on this issue? If yes, till when can we expect the fix for this to be available?

**Comment by nwbirnie** [comment]
@nisha-goyal hey, we don't have an officially supported version of the shaded artifact as yet. However, you can use the pre-release PR #99 as a template. It's currently setup to shade every dependency except SLF4J. This could be modified to shade only, e.g. guava and protobuf, relocating those packages to avoid namespace collisions.

**Comment by nisha-goyal** [comment]
@nwbirnie hey, Thanks for the reply! We will try things out using the patch on top of client library code.

**Comment by nwbirnie** [comment]
Hey @nisha-goyal did you possibly finish testing with this? Did it work for you?

**Comment by nisha-goyal** [comment]
Hey @nwbirnie Yes we did tweak it for us and got it working for our project. We were having some of the library common, so shaded only those.

**Comment by nwbirnie** [comment]
Great - thanks 👍
