### ISSUE TITLE
Is adwords axis dependency will deprecate on 22 April  ? 

### ISSUE THREAD

**Issue by yogesh-0586** [googleads/google-ads-java#545]
Is this dependency 
`com.google.api-ads:adwords-axis:x.x.x` will deprecate on 22 April or we can continue used same dependency along with ads dependency (`com.google.api-ads:google-ads:x.x.x`)

**Comment by jradcliff** [comment]
Hi,

After the AdWords API sunsets in April, we'll eventually remove the [google-ads-migration-examples ](https://github.com/googleads/google-ads-java/tree/main/google-ads-migration-examples) where that dependency exists. However, the `adwords-axis` dependency is already not a dependency of the main `com.google.api-ads:google-ads:X` module.

We won't be removing the `adwords-axis` modules from Maven central, so any releases that are out there will still be available to use as dependencies. However, once the AdWords API sunsets, you won't be able to use those dependencies to successfully make requests against the AdWords API. If you're depending on the `adwords-axis` module in order to get some of _its dependencies_, I recommend adding those dependencies to your project directly.

Thanks,
Josh
