### ISSUE TITLE
Best way to get account labels

### ISSUE THREAD

**Issue by garuna-m6** [googleads/google-ads-java#556]
**What is your question?**

Hi Team, 

Good morning.

Have a quick documentation related query.

The migration documentation (https://developers.google.com/google-ads/api/docs/migration/features) mentions functionality ManagedCustomer.AccountLabels  can be used using CustomerClient.applied_label_ids . 

I am using AccountLables from Adwords to distinguish between tags like Google PLA/ SEM/ Display accounts, however this functionality lists me a set of  labels like "customers/{accountId}/labels/{labelId}.

My questions against these are:
- For testing purposes I extracted all these label ids manually, what is the better parse it ?
- To check the labels name it requires two separate requests one to customer_client and other to labels, is there a better way to do it in one query, shouldn't this functionality be under customer_label table ?
- Any reference for query builder lib com.google.api.ads.admanager.lib.utils.QueryBuilder  , how to use the IN clause ?
- Just confirming google ads api doesn't provide a join operation in gaql
Thanks

**Comment by jradcliff** [comment]
Hi,

I recommend the following approach:

1. Since the set of labels in your account is unlikely to change frequently, retrieve and _cache_ the list of `Label` objects by running a query:

        SELECT 
          label.id, 
          label.name, 
          label.resource_name, 
          label.status 
        FROM label

1. When retrieving `CustomerClient` objects, use the `label.resource_name` from the first step to look up `label.name` or filter the list of `CustomerClient.applied_labels`. The `applied_labels` field contains resource names, so you should not have to parse out the ID.

The Google Ads API does not support custom `JOIN` operations, and currently does not support retrieving label attributes such as `label.name` in queries against other entities. We're aware there is interest in adding that functionality, however.

Thanks,
Josh
