### ISSUE TITLE
Dependency netty-tcnative-boringssl-static version too low

### ISSUE THREAD

**Issue by yuanlu-0** [googleads/google-ads-java#557]
**Describe the issue:**
I tried to use a Micronaut HTTP client together with this google ads API in the same repo, and ran into [ClassNotFoundException AsyncSSLPrivateKeyMethod](https://stackoverflow.com/questions/69102335/upgrade-to-micronaut-3-0-failed-for-http-client-classnotfoundexception-asyncssl) with the Micronaut HTTP client. The issue here is `google-ads-java` is using `netty-tcnative-boringssl-static` with version `2.0.26-FINAL`, which is very outdated. Can we bump this lib version to the latest?

**Steps to Reproduce:**
Follow [Micronaut HTTP client guide](https://guides.micronaut.io/latest/micronaut-http-client.html) to set up a declarative HTTP client in the same repo as Google Ads Java. Then when the Micronaut HTTP client is called you will get `ClassNotFoundException AsyncSSLPrivateKeyMethod` exception.

**Expected behavior:**
I manually bumped the `netty-tcnative-boringssl-static` version and the issue was resolved.

**Client library version and API version:**
Client library version:
Google Ads API version:
JDK version:

**Request/Response Logs:**

 
**Anything else we should know about your project / environment:**

**Comment by jradcliff** [comment]
Thanks for the detailed issue report. For your use case, would you actually prefer that our library did not declare a `netty-tcnative-boringssl-static` at all? I ask because one approach we could take would be to simply remove that from [google-ads/build.gradle](https://github.com/googleads/google-ads-java/blob/main/google-ads/build.gradle#L59), but I'm curious if that would introduce different issues for you.

Thanks,
Josh, Google Ads API Team

**Comment by jradcliff** [comment]
Dependency on `netty-tcnative-boringssl-static` was removed in [17.0.0](https://github.com/googleads/google-ads-java/releases/tag/17.0.0).
