### ISSUE TITLE
Why is AssetSet without id field

### ISSUE THREAD

**Issue by schabe77** [googleads/google-ads-java#572]
Hi,

I wonder why https://developers.google.com/google-ads/api/fields/v10/asset_set has no ID field. All items that I have worked with so far had a resource name containing the ID as well as a separate numeric ID field. AssetSet is the item that behaves differently there. 

So I just wanted to ask: is it by purpose or was the ID field just forgotten?

Best regards,

Christian

**Comment by jradcliff** [comment]
Hi Christian,

Sorry for the delayed response on this one. We're looking into whether this was an oversight or intentional.

In the meantime as a workaround, you can filter using the `asset_set.resource_name`, and you can parse and construct those names using the [`AssetSetName` class](https://github.com/googleads/google-ads-java/blob/main/google-ads-stubs-v10/src/main/java/com/google/ads/googleads/v10/resources/AssetSetName.java).

Thanks,
Josh

Ref: b/222679964

**Comment by schabe77** [comment]
Yes, that's exactly how I do it:
```Long.valueOf(AssetSetName.parse(assetSet.getResourceName()).getAssetSetId());```
 So there is no hurry, I was just interested.

**Comment by jradcliff** [comment]
Cool, so you're way ahead of me. :smile: Thanks for pointing this out, though. It does seem a bit strange that we don't expose that field directly.

**Comment by jradcliff** [comment]
The `asset_set.id` field was added in v10_1.

https://developers.google.com/google-ads/api/fields/v10/asset_set#asset_set.id

Apologies for the delayed update on this.

Cheers,
Josh
