### ISSUE TITLE
ListAccessibleCustomers is taking approx 60 min before giving exception if called with incorrect Refresh Token

### ISSUE THREAD

**Issue by AnuragKSinha** [googleads/google-ads-java#595]
**Describe the bug:**
When we are using an incorrect refresh token or expired refresh token it takes a lot of time before giving an exception(60 mins approx or even more) and hence causing a 504 TIMEOUT. Also, there is a limitation on the number of refresh tokens that we can create which is at max [50 refresh tokens at a time and if we create a new 51st refresh token then the oldest one will expire](https://developers.google.com/identity/protocols/oauth2#expiration). And hence chances of getting into this issue is more likely.
 
**Steps to Reproduce:**

We tried calling [listaccessiblecustomers ](https://developers.google.com/google-ads/api/reference/rpc/v10/CustomerService#listaccessiblecustomers). And we were expecting to get some invalid Exception in some ms or some secs so that we can log it for Error notification to our customers instead, after calling the API the call got stuck for almost 61 mins and then 504 TIMEOUT occurred.

**Expected behavior:**

we were expecting to get some invalid Exception in some ms or some secs so that we can log it for Error notification to our customers instead, after calling the API the call got stuck for almost 61 mins, and then 504 TIMEOUT occurred.

**Client library version and API version:**
Client library version: 
Google Ads API version: v9
JDK version: 1.8

**Request/Response Logs:**

 
**Anything else we should know about your project / environment:**

**Comment by jradcliff** [comment]
Hi,

The timeout issue you mentioned is due to #169, where we're coordinating on a fix with other dependency owners. In the meantime, if you want to proactively check if a refresh token is valid _before_ issuing any requests, you could call `refreshAccessToken()` on the `Credentials` of the `GoogleAdsClient`. See the [workaround in #169](https://github.com/googleads/google-ads-java/issues/169#issuecomment-905145900).

The 50 refresh tokens limit is per `(GoogleAccount, ClientID)` pair. Once you have a refresh token for such a pair, I'd recommend storing that refresh token securely somewhere, and then retrieving it from storage the next time you need to issue an API request on that user's behalf. That will be far more efficient and less cumbersome than obtaining a new refresh token every time.


Thanks,
Josh
