### ISSUE TITLE
API to get counts of various entities

### ISSUE THREAD

**Issue by akshayb-pcln** [googleads/google-ads-java#629]
We want to be able to show on dashboard how much of the data we already have synced and is readily available to access in our internal system.
Currently, we need to check the Google Ads UI -> choose account -> choose entity -> scroll all the way down at the bottom and wait for the number to load.

Fairly enough, Google Ads UI is using some kind of api to get that count and it would really help us to if we get access to the same.

**Comment by devchas** [comment]
Hi @akshayb-pcln would you please send this request to our general support team at googleadsapi-support@google.com? The reason I ask is that this is a core API feature request rather than one that is specific to the client library. When you do send that request, I would suggest including a screenshot of the feature in the UI because it is not clear to me what you are referring to.
