### ISSUE TITLE
AdGroup AudienceSetting setUseAudienceGrouped false Does Not Work on Create

### ISSUE THREAD

**Issue by PeterLavetsky** [googleads/google-ads-java#680]
```
implementation "com.google.api-ads:google-ads:22.0.0
```

```
request-id=Z11g-189celsaSzopO3mPA
```

```
adGroup.setAudienceSetting(AudienceSetting.newBuilder().setUseAudienceGrouped(false).build());
```

```
final AdGroupOperation.Builder operationBuilder = AdGroupOperation.newBuilder();
operationBuilder.setCreate( adGroup );
```

Generates a create request without the use_audience_grouped field:

```
Request
-------
MethodName: google.ads.googleads.v12.services.AdGroupService/MutateAdGroups
Endpoint: googleads.googleapis.com:443
Headers: REDACTED, x-goog-api-client=gl-java/11.0.15 gccl/22.0.0 gapic/22.0.0 gax/2.16.0 grpc/1.45.1 pb/3.19.6}
Body: customer_id: "REDACTED"
operations {
  create {
REDACTED
    audience_setting {
    }
  }
}
partial_failure: true


Response
--------
Headers: Metadata(content-disposition=attachment,content-type=application/grpc,request-id=Z11g-189celsaSzopO3mPA,date=Fri, 23 Dec 2022 16:06:20 GMT,alt-svc=h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43")
Body: results {
  resource_name: REDACTED
}
```

The AdGroup is created, however the use_audience_grouped attribute is created as true, which is the default and is immutable post create:

```
https://developers.google.com/google-ads/api/reference/rpc/v12/AdGroup.AudienceSetting#use_audience_grouped
```

If we don't set the AudienceSetting on create, the use_audience_grouped attribute is still set to true on the created object.

If we set the use_audience_grouped attribute to true on create the request accurately has the use_audience_grouped setting included:

```
audience_setting {
  use_audience_grouped: true
}
```

Another user posted similar findings in the API Group:

```
https://groups.google.com/g/adwords-api/c/V5QjYechzHs/m/dcwmK8R7DgAJ
```

We've manually manipulated the update_mask in the past on update operations, but that procedure doesn't look available to us for a  create.

Looking for guidance on a workaround or estimated delivery of a patched Java client library.

Thanks
Pete

**Comment by jradcliff** [comment]
Hi @PeterLavetsky ,

Apologies for the late response. I missed this due to the holidays.

The issue here is actually an API issue, and stems from the fact that the `use_audience_grouped` field does not have the `optional` keyword. As a result, when processing an operation on our side, we cannot tell the difference between:

a) The `use_audience_grouped` field was explicitly set to `false`.

and

b) The `use_audience_grouped` field was not explicitly set by you.

If the field was marked `optional`, then we could differentiate between a) and b) via the `hasUseAudienceGrouped()` method. In fact, you can see this "in action" by comparing the `AudienceSettingOrBuilder` in `Campaign.java`, where [`hasUseAudienceGrouped()`](https://github.com/googleads/google-ads-java/blob/5fcf3d0004721b7658207a7284cb1df17abd7b5c/google-ads-stubs-v12/src/main/java/com/google/ads/googleads/v12/resources/Campaign.java#L10196) *exists*, to the same type in `AdGroup.java`, where [`hasUseAudienceGrouped()`]( https://github.com/googleads/google-ads-java/blob/5fcf3d0004721b7658207a7284cb1df17abd7b5c/google-ads-stubs-v12/src/main/java/com/google/ads/googleads/v12/resources/AdGroup.java#L66) does *not* exist. The reason for this is that the [`Campaign` proto](https://github.com/googleapis/googleapis/blob/2c7756f6228b12867e88496f047dff6331712799/google/ads/googleads/v12/resources/campaign.proto#L237) declares the field as:

`    optional bool use_audience_grouped = 1 [(google.api.field_behavior) = IMMUTABLE];`

while the [`AdGroup` proto](https://github.com/googleapis/googleapis/blob/2c7756f6228b12867e88496f047dff6331712799/google/ads/googleads/v12/resources/ad_group.proto#L54) declares it as:

`    bool use_audience_grouped = 1 [(google.api.field_behavior) = IMMUTABLE];`

What _should_ happen in this case is that the API should treat a) and b) the same, which ultimately means that the default value _should_ be `false`. I have filed a bug on this to fix the ad group case. Could you share the subject line of the support email or post so I can tag it accordingly and we can follow up with you from there?

One final note: when a field is *not* `optional` and is set to the default value for its data type, the protobuf library doesn't print it in output or serialize it on the wire. See the [protobuf language guide](https://developers.google.com/protocol-buffers/docs/proto3#default) for more details.

Thanks,
Josh, Google Ads API Team

**Comment by PeterLavetsky** [comment]
Thanks for the update Josh

```
Could you share the subject line of the support email or post so I can tag it accordingly and we can follow up with you from there?
```

I'm not sure what this is in reference to. I've only posted about this issue here and haven't contacted any team at Google via other methods.

Thanks, and Happy New Year
Pete

**Comment by jradcliff** [comment]
Hi Pete,

Happy New Year to you as well! Sorry, I misunderstood and for some reason thought you had contacted API support about this.

Since this is an issue with the API, please subscribe to the forum thread you mentioned: https://groups.google.com/g/adwords-api/c/V5QjYechzHs/m/dcwmK8R7DgAJ. I'll provide updates there as I hear back on the bug.

Thanks,
Josh
