### ISSUE TITLE
Extract requestId on UploadClickConversionsResponse 

### ISSUE THREAD

**Issue by julienmouyal** [googleads/google-ads-java#709]
Most of the endpoints that I see have a `requestId` as a field of the response, but it seems that in the case in the case of `UploadClickConversionsResponse`, there is no way to access the requestId unless it's attached to a `GoogleAdsException`, which is not thrown in the case of partial failures.

How can I access that field using the Java library?

**Comment by jradcliff** [comment]
Hi,

The only response type I'm aware of that has `request_id` as a *field* is [SearchGoogleAdsStreamResponse](https://developers.google.com/google-ads/api/reference/rpc/v13/SearchGoogleAdsStreamResponse). For everything else, the request ID is returned as a [trailing metadata header named `request-id`](https://developers.google.com/google-ads/api/docs/concepts/call-structure#response_headers). `SearchGoogleAdsStreamResponse` is a special case because it's for a streaming request.

The library logs request IDs for every request, and you can see how that's implemented in [LoggingInterceptor](https://github.com/googleads/google-ads-java/blob/main/google-ads/src/main/java/com/google/ads/googleads/lib/logging/LoggingInterceptor.java). You could try something similar, but that would require adding your own `io.grpc.ClientInterceptor`, which isn't exactly straightforward.

Backing up a bit, could you elaborate on *why* you want to programmatically capture the request ID?

Thanks,
Josh, Google Ads API Team

**Comment by julienmouyal** [comment]
Thank you for your explanation @jradcliff, it's true I was always looking at `SearchGoogleAdsStreamResponse`. We will try building the client using our own ClientInterceptor. 

The reason for our need is that in the case of an issue or a partial failure, GoogleAds support will ask for the `request_id` and we are not able to provide it to them at the moment.

**Comment by julienmouyal** [comment]
Our ideal would be to access that field and store it easily on our side, but enabling the logging can be a decent workaround.

Thank you

**Comment by julienmouyal** [comment]
We ended up using the rest api for that endpoint. We will revert back to grpc if this is available in further release. 

Thanks,
Julien

**Comment by jradcliff** [comment]
Hi Julien,

We recently released a fix in the API so the server will populate the request ID on the partial failure error.

You can get to this value as follows:

```
      if (response.hasPartialFailureError()) {
        GoogleAdsFailure googleAdsFailure =
            ErrorUtils.getInstance().getGoogleAdsFailure(response.getPartialFailureError());

        // Prints the request_id from the partial failure error.
        String requestId = googleAdsFailure.getRequestId();
        System.out.printf(
            "response.partial_failure_error.request_id: %s%n", requestId);
        // Prints the message from each partial failure error.
        googleAdsFailure
            .getErrorsList()
            .forEach(e -> System.out.println("Partial failure occurred: " + e.getMessage()));
      }
```

Cheers,
Josh
