### ISSUE TITLE
Returns an "The error code is not in this version." error when attempting to create a CampaignCriterion or AdGroupCriterion for a user list

### ISSUE THREAD

**Issue by nick-evocalize** [googleads/google-ads-java#710]
**Describe the bug:**

When attempting to create a `CampaignCriterion` or `AdGroupCriterion` for a user list, we get back this error:
```
errors {
  error_code {
    request_error: UNKNOWN
  }
  message: "The error code is not in this version."
  trigger {
    int64_value: 608470695
  }
  location {
    field_path_elements {
      field_name: "operations"
      index: 0
    }
    field_path_elements {
      field_name: "create"
    }
    field_path_elements {
      field_name: "user_list"
    }
    field_path_elements {
      field_name: "user_list"
    }
  }
}
request_id: "43QiLDbEVYLA1XslVSbeEA"
```

We are on the latest SDK version (`25.0.0`) and also using the latest version of the objects (v13).

These calls were previously working just fine and only recently broke, so something is probably wrong with the API itself too. However, `The error code is not in this version.` makes it sound like this SDK is out of sync with the API, so I figured I would open a bug report here for that.

**Steps to Reproduce:**

1. Create a campaign. So far, I've tried both search and discovery and am getting this issue for both.
2. Create an ad group under that campaign
3. Create a user list.
4. Create an `AdGroupCriterion` that links that user list to the ad group.

The code for creating a user list and ad group criterion from your documentation can be used to reproduce
this issue. Here's a link: https://developers.google.com/google-ads/api/docs/remarketing/audience-types/website-visitors

**Expected behavior:**

Creates an ad group criterion instead of returning an error.

**Client library version and API version:**
Client library version: 25.0.0
Google Ads API version: v13
JDK version: 1.8

**Request/Response Logs:**
request ID: `43QiLDbEVYLA1XslVSbeEA`

**Comment by jradcliff** [comment]
Hi,

Thanks for providing a detailed explanation of the issue. I looked up that particular request and the underlying error was `CANNOT_TARGET_SIMILAR_USER_LIST`.

You're getting this error because `608470695` is an automatically created user list of type `SIMILAR`. Per our [blog post from November 2022](https://ads-developers.googleblog.com/2022/11/announcing-deprecation-and-sunset-of.html), you can no longer target or exclude `SIMILAR` user lists.

However, that error *should* have been published in the Google Ads API so that this library would pick up the enum. I'm following up on getting that fixed in a future release.

Thanks,
Josh

**Comment by nick-evocalize** [comment]
@jradcliff Got it, thanks for the quick/detailed response!

**Comment by nick-evocalize** [comment]
Hey @jradcliff , there might be a second error code that is missing from the client library as well. I get that `The error code is not in this version.` response when attempting to link a website-visitors (rule-based) (not `SIMILAR`) audience to an ad group. Would you mind checking the error code for request ID `OpHGjxaPtS5j6rpOOuZHhg` as well?

**Comment by jradcliff** [comment]
Thanks for highlighting that one as well. It turns out that this is due to the fact that the AdGroup has [`audience_setting.use_audience_grouped`](https://developers.google.com/google-ads/api/reference/rpc/v13/AdGroup.AudienceSetting#use_audience_grouped) set to `true`. As a result, your audience targeting on that ad group must be configured using `AudienceInfo` criteria (pointing to an `Audience`) instead of `UserListInfo`.

Regardless, we definitely should be returning a more useful error in this situation. :grin: I'm following up on that.

Cheers,
Josh

**Comment by nick-evocalize** [comment]
@jradcliff Thank you so much for the quick response on that!

**Comment by jradcliff** [comment]
FYI, v14 of the Google Ads API added that `CANNOT_TARGET_SIMILAR_USER_LIST` error:

https://developers.google.com/google-ads/api/diff-tool/v14/versus-v13/diffs/errors/criterion_error
