### ISSUE TITLE
gRPC call hanging even with timeout set

### ISSUE THREAD

**Issue by julienmouyal** [googleads/google-ads-java#722]
We are looking to implement timeouts on every gRPC call we are making to the GoogleAds API. Following the documentation, we are now using the callable endpoints like in the snippet bellow : 

```
                response =
                        googleAdsServiceClient.searchPagedCallable()
                                .call(
                                        SearchGoogleAdsRequest.newBuilder()
                                                .setQuery(query)
                                                .setCustomerId(Long.toString(loginCustomerId))
                                                .build(),
                                        GrpcCallContext.createDefault()
                                                .withTimeout(Duration.ofMillis(30000)));
```

However, it seems that when the refresh token is invalid, the call hangs for much longer than the timeout. Is there a way to enforce the timeout in that case or maybe test it with another call? This is problematic because it locks a thread for too long and compromise the server ability to answer other calls.

**Comment by jradcliff** [comment]
One simple way to do this is, before you make any Google API request, refresh the `Credentials` on your `GoogleAdsClient`.

For example, if you have a `GoogleAdsClient` instance named `googleAdsClient`, put this before your call to `searchPagedCallable()`:

```
    ((com.google.auth.oauth2.OAuth2Credentials)googleAdsClient.getCredentials()).refreshIfExpired();
```

That will throw a `com.google.auth.oauth2.GoogleAuthException` if the refresh token is invalid, like this:

```
Exception in thread "main" com.google.auth.oauth2.GoogleAuthException: com.google.api.client.http.HttpResponseException: 400 Bad Request
POST https://oauth2.googleapis.com/token
{
  "error": "invalid_grant",
  "error_description": "Token has been expired or revoked."
}
```

The difference with this approach is that you are explicitly verifying the refresh token is valid instead of relying on the `GoogleAdsServiceClient` to do so.

Hope that helps!

Josh, Google Ads API Team
