### ISSUE TITLE
Client hangs on UploadImage

### ISSUE THREAD

**Issue by devchas** [googleads/google-ads-java#74]
I just wrote an UploadImage example and tried running it against v1. There seems to be a bug with the MediaFile service client where the client hangs and never responds after making the mutate request to upload an image. The request does complete, however, which I can verify by running a query to get all images.

**Comment by jradcliff** [comment]
Oddly enough, I'm not able to reproduce this behavior. The only changes I made to your example were to simplify the dependencies as follows:

1. Removed the dependency on `com.google.api-ads:ads-lib`.
1. Instead of using `com.google.api.ads.common.lib.utils.Media` to get the byte array from the URL, used the following snippet:

        byte[] imageData = ByteStreams.toByteArray(new URL(
              "https://goo.gl/3b9Wfh").openStream());

Could you try the same and let me know if you still don't get a response?

Thanks,
Josh

**Comment by devchas** [comment]
Removing that dependency seems to fix the problem.
