### ISSUE TITLE
creating client 

### ISSUE THREAD

**Issue by rotemzluf123** [googleads/google-ads-java#745]
Hi,
I want to upload identifiers to a specific audience (user list) / get user list size. As a first step, I create a client. For that, I am looking for the manager account and set the loginCustomerId to be the manager account. My question is, should I look for the manager account of my client every time before an action? or is it a persistent value of my client that I can save? like the refresh token
Thanks.

**Comment by jradcliff** [comment]
Hi,

I'd recommend reading this section of the [guide](https://developers.google.com/google-ads/api/docs/concepts/call-structure#cid) that explains the purposed of the login customer ID. As that guide mentions:

> Setting the `login-customer-id` is equivalent to choosing an account in the Google Ads UI after signing in or clicking on your profile image at the top right.

So if you're always using the same OAuth credentials (refresh token) that accesses the `customer_id` via access through the same manager account, the login customer ID is unlikely to change unless someone revokes that user's access to the manager account.

If you determine that the credentials you're using will always be for access through a specific manager account, then you can add the `api.googleads.loginCustomerId` line mentioned in our [configuration guide](https://developers.google.com/google-ads/api/docs/client-libs/java/config-file).

Cheers,
Josh, Google Ads API Team

**Comment by rotemzluf123** [comment]
Hi, thanks, it helped. Another question: What is the easiest way to check if my customer ID is a manager? And is it true that for that customer, the loginCustomerId is equal to the account ID?

**Comment by jradcliff** [comment]
Hi,

The query `SELECT customer.id, customer.manager FROM customer` will return the boolean `manager` field that indicates if a customer is a manager.

> And is it true that for that customer, the loginCustomerId is equal to the account ID?

An example may help. Let's say your account hierarchy is as follows, with M1, M2, and M3 as manager accounts, and C1 as a client (non-manager) account:
```
┌──┐   
│M1│   
└┬─┘   
┌┴───┐ 
│ M2 │ 
└┬──┬┘ 
┌┴─┐│  
│M3││  
└┬─┘│  
┌┴──┴─┐
│ C1  │
└─────┘
```

Recall that when you generate OAuth credentials, you are generating them for a specific user `U`. The `loginCustomerId` should be set to the account where `U` is listed as a direct user, so when making requests where the `customer_id` is `C1`:

* If `U` is *only* a user in `M1`, then use `M1` as the `loginCustomerId`. Setting it to `M2`, `M3`, or `C1` would fail because `U` does not have direct access to those accounts.
* If `U` is *only* a user in `M2`, then use `M2` as the `loginCustomerId`. Setting it to `M1`, `M3`, or `C1` would fail.
* If `U` is *only* a user in `M3`, then use `M3` as the `loginCustomerId`. Setting it to `M1`, `M2`, or `C1` would fail.
* If `U` is *only* a user in `C1`, then use `C1` as the `loginCustomerId`. Setting it to `M1`, `M2`, or `M3` would fail. In this scenario, you could also not specify the `loginCustomerId`, as it will default to the `customer_id` of `C1`.

It gets more complicated if `U` is a user on multiple accounts in the hierarchy. For example, if `U` is a user in `M1` and `M3`, then you could set `loginCustomerId` to either `M1` or `M3` for most use cases. However, there are some use cases  where you would need to choose `M1` instead of `M3`. For example, if you are uploading conversion adjustments and the Google Ads conversion customer is `M1`, you'd need to set `loginCustomerId` to `M1`.

Thanks,
Josh, Google Ads API Team

**Comment by rotemzluf123** [comment]
Okay, thanks a lot. I'm sorry to bother you, but I have another small question. I want to retrieve the size of a user list every day for my customer. To achieve this, I plan to search for a manager account once, save it, and use it in the next days. What is the easiest way to check daily that the manager account is still valid for my customer, so I don't need to look for a new one?

**Comment by jradcliff** [comment]
If you have OAuth credentials for user `U` and you're using them to access customer `C` with `loginCustomerId` set to manager `M`, you could run [`listAccessibleCustomers`] each day to verify that `U` is still a user on `M`, and then run a query against `customer_client` to verify that `C` is still in the hierarchy under `M`. The code sample below demonstrates how to do this:

https://developers.google.com/google-ads/api/samples/get-account-hierarchy

The [Get Account Hierarchy] guide walks through this process in detail.

[`listAccessibleCustomers`]: https://developers.google.com/google-ads/api/reference/rpc/v15/CustomerService#listaccessiblecustomers
[Get Account Hierarchy]: https://developers.google.com/google-ads/api/docs/account-management/get-account-hierarchy

**Comment by jradcliff** [comment]
Closing this out since there haven't been updates in a few weeks.
